license="MIT"
modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Harleyoc1/DynamicTreesTerraForged/issues"

[[mods]]
modId="dtterraforged"
version="${file.jarVersion}"
displayName="Dynamic Trees for TerraForged"
updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/TerraForged.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-terraforged"
logoFile="dtt-logo.png"
credits=""
authors="Harley O'Connor"
description='''
Adds Dynamic Trees compatibility to TerraForged.
'''

[[dependencies.dtterraforged]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtterraforged]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtterraforged]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[0.11.0-Beta6,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtterraforged]]
    modId="dynamictreesplus"
    mandatory=false
    versionRange="[0.1.0-Beta2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtterraforged]]
    modId="terraforged"
    mandatory=true
    versionRange="[0.3.0,)"
    ordering="AFTER"
    side="BOTH"
